### PR TITLE
Hide/Show the ribbon according to the guy visibility

### PR DESCRIPTION
**Pull request by Momegica**

### CODE REVIEW

**Comment by lukeedw** [comment]
Would it be possible to actually hide the ribbons rather than minimising them?  My concern is that the titles are still there across the top.  So we haven't turned all the GUI off.

**Comment by Momegica** [comment]
I don't think it's possible, I've seen no function in Pmill or pshape to do that.

**Comment by lukeedw** [comment]
OK, so we need to modify DelcamProductHost line 225 to be:
`        If (_product IsNot Nothing) Then`
`            'Size should be different depending on whether GUI is shown or hidden`
`            If (_product.IsLooseEmbedded) Then`
`                SetWindowPos(_applicationHandle, HWND_TOP, 0, 0, Me.ActualWidth, Me.ActualHeight, SWP_NOACTIVATE)`
`            ElseIf (_application.Version.Major >= 2018)`
`                SetWindowPos(_applicationHandle, HWND_TOP, - 10, - 60, Me.ActualWidth + 20, Me.ActualHeight + 70, SWP_NOACTIVATE)`
`            Else`
`                SetWindowPos(_applicationHandle, HWND_TOP, - 10, - 30, Me.ActualWidth + 20, Me.ActualHeight + 40, SWP_NOACTIVATE)`
`            End If`
`        End If`
Otherwise the top titles will still show when running applications embedded.

**Comment by Momegica** [comment]
Ok, I will change it but the problem is that the Version.Major for Pmill is 2018, but for Pshape it's 18

So, can we know what is the current product ? with a property like _product.???

**Comment by Momegica** [comment]
Or maybe check the _product.version.major.length, if it's 4, then check with 2018, if it's 2, then compare with 18 ?

**Comment by lukeedw** [comment]
Yes, that should work I think.

**Pull request merged**
