### PR TITLE
Fix outputting closed Polylines to Duct Picture files.

### PR DESCRIPTION
**Pull request by Jonimoose**
When outputting closed polylines to Duct .pic files the first point is duplicated at the end of the pic file but the count is not incremented so on import that last point is ignored and thus it is marked as open.

This fixes this by creating a trueCount variable that is incremented by 1 if the polyline is closed.

Signed-off-by: Jon Sturm <JSturm@programmingplus.com>

### CODE REVIEW

**Comment by davidmn** [comment]
Is it possible to add a test? Say create a polyline, export as pic, reimport and verify the closed state?

**Comment by Jonimoose** [comment]
@davidmn This work for that?

**Comment by lukeedw** [comment]
@Jonimoose did you receive my email about contributing?  Please can you sign one of the contributor documents in the "contributor" folder and email it to me at luke.edwards@autodesk.com?

**Comment by Jonimoose** [comment]
Luke,

No I did not receive your email. I will print that out and sign it and get it sent you to.

**Comment by Jonimoose** [comment]
@lukeedw I sent the email with that. Sorry for the delay, work has had me traveling so I didn't have regular access to a scanner and printer until this week.

**Pull request merged**
