### PR TITLE
Upper and lower tip radius from tipped disc tool

### PR DESCRIPTION
**Pull request by Feuerbowle**
Here is the code as mentioned in issue #24

### CODE REVIEW

**Comment by lukeedw** [comment]
Would you be able to add a test?  Something like this one:
https://github.com/Autodesk/PowerShapeAndPowerMillAPI/blob/d04ff9c6151872e969cc0bd063df783adb6e51e5/Delcam.ProductInterface.PowerMILL.Test/PMEntityTests/PMToolTest.cs#L362

**Comment by Feuerbowle** [comment]
OK, i have such an test now. Should i add the file to my fork and create a new pull request or is it possible to add the file to this pull request?

**Comment by lukeedw** [comment]
If you commit it to the fork then it should automatically update the Pull Request…

**Comment by Feuerbowle** [comment]
Thanks Luke. Wasn't 100% sure but now the test should be in the request

**Pull request merged**
